-- 短链接表，提供短链接服务
DROP TABLE IF EXISTS `DB_BASE`.TBL_SHORT_LINK;
CREATE TABLE `DB_BASE`.TBL_SHORT_LINK (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  SHORT_LINK VARCHAR(128) NOT NULL COMMENT '生成的短链接',
  TARGET_LINK VARCHAR(256) NOT NULL COMMENT '目标链接',
  QUERY_STRING VARCHAR(128) COMMENT '连接中的查询字符串',
  CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
  REMARK VARCHAR(256) COMMENT '备注信息',
  QRCODE VARCHAR(128) COMMENT '二维码图片地址',
  USERNAME VARCHAR(32) COMMENT '创建用户'
) COMMENT '短链接表';